apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    service: service
spec:
  selector:
    service: service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP