apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mysql-deployment
  labels:
    app: mysql
    service: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      service: service
  template:
    metadata:
      labels:
        app: mysql
        service: service
    spec:
      containers:
      - name: service-mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootpassword'
