apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  labels:
    app: mysql
    service: service
spec:
  selector:
    app: mysql
    service: service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP